### ISSUE TITLE
Add additional assertions (List assertions in the descriptions)

### ISSUE THREAD

**Issue by VadimNastoyashchy** [VadimNastoyashchy/real-test-js#45]
Add additional assertions:
- [x] `.toBeNull()`
- [x] `.toBeNotNull()`
- [x] `.toBeUndefined()`
- [x] `.toBeNaN`
- [x] `.toContain(item)`
- [x] `.toMatch(regexp | string)`
- [x] `.toBeGreaterThan()` - number
- [x] `.toBeLessThan()` - number

**Comment by VadimNastoyashchy** [comment]
- `toBeGreaterThan()` - number
- `toBeLessThan()` - number

**Comment by Thulrig** [comment]
PR #79 - were added 6 assertions:
 .toBeNotNull()
 .toBeUndefined()
 .toBeNaN
 .toBeGreaterThan() - number
 .toBeLessThan() - number

**Comment by VadimNastoyashchy** [comment]
https://github.com/VadimNastoyashchy/real-test-js/pull/95
